package com.company.hrsystem.mapper;

import com.company.hrsystem.model.SystemAccount;
import com.company.hrsystem.model.SystemAccountExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SystemAccountMapper {

    // generated by MyBatis Generator
    long countByExample(SystemAccountExample example);

    // generated by MyBatis Generator
    int deleteByExample(SystemAccountExample example);

    // generated by MyBatis Generator
    int deleteByPrimaryKey(Integer systemAccountId);

    // generated by MyBatis Generator
    int insert(SystemAccount row);

    // generated by MyBatis Generator
    int insertSelective(SystemAccount row);

    // generated by MyBatis Generator
    List<SystemAccount> selectByExample(SystemAccountExample example);

    // generated by MyBatis Generator
    SystemAccount selectByPrimaryKey(Integer systemAccountId);

    // generated by MyBatis Generator
    int updateByExampleSelective(@Param("row") SystemAccount row, @Param("example") SystemAccountExample example);

    // generated by MyBatis Generator
    int updateByExample(@Param("row") SystemAccount row, @Param("example") SystemAccountExample example);

    // generated by MyBatis Generator
    int updateByPrimaryKeySelective(SystemAccount row);

    // generated by MyBatis Generator
    int updateByPrimaryKey(SystemAccount row);
    
    List<SystemAccount> selectAll();

    SystemAccount findSystemAccountByEmail(String email);
}